_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 20
lr:
    value: 0.001
optimizer:
    value: Adam
