# config.yaml

oran_env:
  center_freq: 850e6              # Hz
  bandwidth: 20e6                 # Hz
  bandwidth_per_rb: 2e5           # Hz
  num_gnb: 7
  num_rbs: 100
  inter_distance_gnb: 1700        # m
  num_ues_per_gnb: 9
  power_max: 15                   # dBm
  tti: 1e-3                       # s
  noise_power_density: 3.98e-21   # W/Hz

drl_agent:
  max_step: 50
  num_episodes: 500
  last_n: 10
  actor_lr: 3e-4
  critic_lr: 1e-3
  dqn_lr: 1e-3
  gamma: 0.99
  epsilon: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.99
  state_space: 85
  action_space: 2**7


